### ISSUE TITLE
Deploy to Vercel and add MongoDB Atlas

### ISSUE THREAD

**Issue by jgarth** [Trntannan/2-School-Front#1]
It would be great to see the app online and verify everyone's pushes don't break anything. Outside of writing good tests there is always automatic deployment. We call this process Continuous Integration.

Checkout Vercel for deployment and MongoDB Atlas for free NextJS hosting and free database hosting. See https://vercel.com/integrations/mongodbatlas

The deployment on Vercel will then be called: **production environment**.

Acceptance
- [x] Deploy once to Vercel
- [x] Add MongoDB atlas to the Vercel project
- [x] Add mongoose to project and ensure that on production, the correct credentials are used for it
- [x] Setup continuous deployment via GitHub action

**Comment by Trntannan** [comment]
User 'render' purely because the UI was to my prefference as apposed to vercel. added mongoDB, maintained via mongoDB compass.  added mongoose to project initially to impement schema's
